deploy-job: # This job runs in the deploy stage.
  tags:
    - "docker"
  only:
    - "main"
  image: alpine:3.19
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - ssh -o PubkeyAcceptedKeyTypes=+ssh-rsa -o StrictHostKeyChecking=no root@$ALFA_SERVER "
      cd ~/ &&
      rm -rf ./talent-landing &&
      git clone git@gitlab.com:alfabc/talent-landing.git -b main talent-landing &&
      cd ~/talent-landing &&
      chmod +x ./deploy.sh &&
      ./deploy.sh"
