version: "3.3"
services:
  landing_service:
    build:
      context: ../../
      dockerfile: ./ci/prod/dockerfile
    restart: always
    container_name: landing_service
    environment:
      PORT: 4001
    expose:
      - "4001"
    networks:
      - traefik_network

networks:
  traefik_network:
    external: true
